version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/dapp'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - uuhnaut69
    assignees:
      - uuhnaut69
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `npm` packages
  - package-ecosystem: gradle
    directory: '/authentication'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - uuhnaut69
    assignees:
      - uuhnaut69
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope